# This is a basic workflow to help you get started with Actions

name: TEST ACTION

# Controls when the action will run. 
on:
  push:
    tags:
      - 'v*.*.*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Remove files
        run: |
          rm src/test.py

      - name: Install pigar library
        run: |
          pip install pigar
          
      - name: Create requirements with pigar library
        run: |
          yes | pigar -p prod-requirements.txt -P src
      
      - name: Get current tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        
      - name: Output tag
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      
      - name: Push prod-tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin --delete release
          git checkout -b release
          git add . 
          git commit -m "Pushing release ${{ steps.vars.outputs.tag }}-prod"
          git push -u origin release
          git tag -a ${{ steps.vars.outputs.tag }}-prod -m "${{ steps.vars.outputs.tag }}-prod"
          git push origin ${{ steps.vars.outputs.tag }}-prod

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}-prod
