# This is a basic workflow to help you get started with Actions

name: TEST ACTION

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Remove files
        run: |
          TMP_FOLDER=".tmp_engine/"
          mkdir "$TMP_FOLDER"
          cp -R src "$TMP_FOLDER"
          rm src/test.py
          
      - name: Create requirements
        run: |
          python -m pip install pigar
          python -m pigar -p prod-requirements.txt -P src
          
      - name: Remove tmp folder
        run: |
          cp -R "$TMP_FOLDER/tvmodels/" tvmodels
          rm -rf "$TMP_FOLDER"
          
      - name: Push prod tag
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git add -A
          git tag -a v1.1.0 -m "my version 1.1.0"
          git push -u origin HEAD
